version: "3"

services: 
  mc_test:
    volumes:
      - "mc_test:/data"
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      INIT_MEMORY: "7G"
      #`MAGMA_CHANNEL: "dev"
      MAX_MEMORY: "20G"
      TYPE: "MAGMA"
      VERSION: "1.12.2"
      MAX_TICK_TIME: "-1"
      #MODPACK: "https://media.forgecdn.net/files/3377/168/ABOE+-+Server+-+v3.9.4b.zip"
    tty: true
    stdin_open: true
    #restart: unless-stopped

volumes:
  mc_test: 
